# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title: OwnYou
description: OwnYou docs and material related to architecture.
lang: en

# Site subpath, e.g. /blog
# baseurl: "/docs"
baseurl: ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Site base hostname & protocol, e.g. http://example.com
# url: ""
url: "https://www.ownyou.io"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: ownyou_logo_24b.png

navbar:
  sticky: true
  search: false

# Default author settings
author:
  name: Nicholas Longcroft
  title: Lead Architect
  avatar:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  Nick:
    name: Nick
    title: " "
    avatar: avatar-nick.png
    url: /docs/nick
  nick:
    name: " "
    title: " "
    avatar: avatar-nick.png
  CTO:
    name: You
    title: CTO
    avatar: avatar-cto4.png
    url: /docs/chief_technology_officer
  # Lead Developer:
  #   name: You
  #   title: Lead Developer
  #   avatar: avatar-ld.png
  Community Manager:
    name: You
    title: Community Builder
    avatar: avatar-cm3.png
    url: /docs/community_builder
  Publisher Lead:
    name: You
    title: Publisher Lead
    avatar: avatar-pl.png
    url: publisher_lead
  Advertiser Lead:
    name: You
    title: Advertiser Lead
    avatar: avatar-al3.png
    url: advertiser_lead
  Blogger One:
    name: " "
    title: OwnYou Blogger One
    avatar: avatar-cto4.png
  Blogger Two:
    name: " "
    title: OwnYou Blogger Two
    avatar: avatar-cm3.png
  Blogger Three:
    name: " "
    title: OwnYou Blogger Three
    avatar: avatar-pl.png
  Blogger Four:
    name: " "
    title: OwnYou Blogger Four
    avatar: avatar-al3.png
  Blogger colour blue:
    name: " "
    title: OwnYou Blogger Blue
    avatar: avatar_logo_b.png
  Blogger colour green:
    name: " "
    title: OwnYou Blogger Green
    avatar: avatar_logo_g.png
  Blogger colour pink:
    name: " "
    title: OwnYou Blogger Pink
    avatar: avatar_logo_p.png
  Blogger colour yellow:
    name: " "
    title: OwnYou Blogger Yellow
    avatar: avatar_logo_y.png
  Blogger colour blue light:
    name: " "
    title: OwnYou Blogger Blue Light
    avatar: avatar_logo_bb.png

# Social icons displayed in footer
social:
  email:
  website:
  facebook:
  discord: https://discord.gg/W5bK2pGu
  dribbble:
  github:
  googleplus:
  instagram:
  linkedin:
  pinterest:
  twitter: https://twitter.com/
  vimeo:
  youtube:

# Share button
share:
  post: true # Display share buttons on a post page
  doc: true # Display share buttons on a doc page
  twitter: nlongcroft # Enable by adding Twitter handle
  facebook: true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
  copyright: Made by <a href="https://OwnYou.io/">OwnYou.io</a> in London.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname:

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate: 25

# Blog path
paginate_path: "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads: /uploads/

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed

collections:
  docs:
    output: true
  faqs:
    output: false
  changelogs:
    output: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: doc
